In [ ]:
import sqlite3

# Connect to the SQLite database
conn = sqlite3.connect('student_db.sqlite')
cursor = conn.cursor()

# Create or update the students table
def create_table():
    cursor.execute('''
    CREATE TABLE IF NOT EXISTS students (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        department TEXT,
        course TEXT,
        year INTEGER,
        address TEXT,
        grade TEXT,
        dob TEXT,  -- Date of Birth (YYYY-MM-DD format)
        phone_number TEXT
    )
    ''')
    conn.commit()

def check_table_schema():
    cursor.execute("PRAGMA table_info(students)")
    columns = cursor.fetchall()
    for column in columns:
        print(column)

def add_student(name, department, course, year, address, grade, dob, phone_number):
    cursor.execute('''
    INSERT INTO students (name, department, course, year, address, grade, dob, phone_number)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ''', (name, department, course, year, address, grade, dob, phone_number))
    conn.commit()

def view_students():
    cursor.execute('SELECT * FROM students')
    rows = cursor.fetchall()
    for row in rows:
        print(row)

def update_student(student_id, name=None, department=None, course=None, year=None, address=None, grade=None, dob=None, phone_number=None):
    if name:
        cursor.execute('''
        UPDATE students
        SET name = ?
        WHERE id = ?
        ''', (name, student_id))
    if department:
        cursor.execute('''
        UPDATE students
        SET department = ?
        WHERE id = ?
        ''', (department, student_id))
    if course:
        cursor.execute('''
        UPDATE students
        SET course = ?
        WHERE id = ?
        ''', (course, student_id))
    if year is not None:
        cursor.execute('''
        UPDATE students
        SET year = ?
        WHERE id = ?
        ''', (year, student_id))
    if address:
        cursor.execute('''
        UPDATE students
        SET address = ?
        WHERE id = ?
        ''', (address, student_id))
    if grade:
        cursor.execute('''
        UPDATE students
        SET grade = ?
        WHERE id = ?
        ''', (grade, student_id))
    if dob:
        cursor.execute('''
        UPDATE students
        SET dob = ?
        WHERE id = ?
        ''', (dob, student_id))
    if phone_number:
        cursor.execute('''
        UPDATE students
        SET phone_number = ?
        WHERE id = ?
        ''', (phone_number, student_id))
    conn.commit()

def delete_student(student_id):
    cursor.execute('''
    DELETE FROM students
    WHERE id = ?
    ''', (student_id,))
    conn.commit()

def main():
    create_table()  # Ensure the table is created with the correct schema
    # check_table_schema()  # Uncomment to debug and view schema

    while True:
        print("\nStudent Database Management System")
        print("1. Add Student")
        print("2. View Students")
        print("3. Update Student")
        print("4. Delete Student")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            name = input("Enter student name: ")
            department = input("Enter department: ")
            course = input("Enter course: ")
            year = int(input("Enter year: "))
            address = input("Enter address: ")
            grade = input("Enter grade: ")
            dob = input("Enter date of birth (YYYY-MM-DD): ")
            phone_number = input("Enter phone number: ")
            add_student(name, department, course, year, address, grade, dob, phone_number)
            print("Student added successfully.")
        elif choice == '2':
            print("Student Records:")
            view_students()
        elif choice == '3':
            student_id = int(input("Enter student ID to update: "))
            name = input("Enter new student name (or leave blank to keep current): ")
            department = input("Enter new department (or leave blank to keep current): ")
            course = input("Enter new course (or leave blank to keep current): ")
            year_input = input("Enter new year (or leave blank to keep current): ")
            year = int(year_input) if year_input else None
            address = input("Enter new address (or leave blank to keep current): ")
            grade = input("Enter new grade (or leave blank to keep current): ")
            dob = input("Enter new date of birth (YYYY-MM-DD) (or leave blank to keep current): ")
            phone_number = input("Enter new phone number (or leave blank to keep current): ")
            update_student(
                student_id,
                name if name else None,
                department if department else None,
                course if course else None,
                year,
                address if address else None,
                grade if grade else None,
                dob if dob else None,
                phone_number if phone_number else None
            )
            print("Student updated successfully.")
        elif choice == '4':
            student_id = int(input("Enter student ID to delete: "))
            delete_student(student_id)
            print("Student deleted successfully.")
        elif choice == '5':
            break
        else:
            print("Invalid choice. Please try again.")

if __name__ == "__main__":
    main()

# Close the connection when done
cursor.close()
conn.close()

Student Database Management System
1. Add Student
2. View Students
3. Update Student
4. Delete Student
5. Exit
Enter your choice: 1
Enter student name: Sneka
Enter department: B.E
Enter course: cse
Enter year: 3
Enter address: 15/334,Srinivasapuram Avinashi
Enter grade: O
Enter date of birth (YYYY-MM-DD): 2004-07-07
Enter phone number: 7667432091
Student added successfully.

Student Database Management System
1. Add Student
2. View Students
3. Update Student
4. Delete Student
5. Exit
Enter your choice: 2
Student Records:
(1, 'Sneka', 'B.E', 'cse', 3, '15/334,Srinivasapuram Avinashi', 'O', '2004-07-07', '7667432091')

Student Database Management System
1. Add Student
2. View Students
3. Update Student
4. Delete Student
5. Exit
Enter your choice: 3
Enter student ID to update: 1
Enter new student name (or leave blank to keep current):
Enter new department (or leave blank to keep current):
Enter new course (or leave blank to keep current): ECE
Enter new year (or leave blank to keep current):
Enter new address (or leave blank to keep current):
Enter new grade (or leave blank to keep current):
Enter new date of birth (YYYY-MM-DD) (or leave blank to keep current):
Enter new phone number (or leave blank to keep current):
Student updated successfully.

Student Database Management System
1. Add Student
2. View Students
3. Update Student
4. Delete Student
5. Exit
Enter your choice: 5